
{'date': 'Fri Jul 10 2020 13:03:11.824 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  document["pydiv"] <= H("Olá", class="title")
                                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 13:21:52.180 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 6
    document.html = SITE
NameError: name 'SITE' is not defined
'''},
{'date': 'Fri Jul 10 2020 13:42:26.259 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: <TypeError: obj is undefined>
'''},
{'date': 'Fri Jul 10 2020 14:28:25.697 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  document.body <= S(D(D(
                                                                                                                                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:28:53.530 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  document.body <= S(D(D(
                                                                                                                                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:32:20.34 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  document.body <= S(D(D(
                                                                                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:44:11.898 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  document.body <= S(D(D(
                                                                                                                                                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:46:18.89 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  body = S(D(D(
                                                                                                                                                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:47:23.406 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  body = S(D(D(
                                                                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:50:55.556 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  body = S(D(D(
                                                                                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 10 2020 14:57:08.127 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  body = S(D(D(
                                                                                                                                                                                         ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 13 2020 13:28:39.500 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 79
    f = Open("nome.txt")
  module <module> line 58
    self.filename = filename
NameError: name 'filename' is not defined
'''},
{'date': 'Mon Jul 13 2020 14:17:23.30 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  self.__enter = dict(
                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 13 2020 14:17:48.261 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  self.__enter = dict(
                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 13 2020 14:19:07.231 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  self.__enter = dict(
                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 13 2020 14:21:03.746 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 60
    with Open("x.txt", "rw") as no:
  module <module> line 31
    raise ValueError("must have exactly one of create/read/write/append mode")
ValueError: must have exactly one of create/read/write/append mode
'''},
{'date': 'Mon Jul 13 2020 14:21:45.876 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 60
    with Open("x.txt", "r") as no:
  module <module> line 31
    raise ValueError("must have exactly one of create/read/write/append mode")
ValueError: must have exactly one of create/read/write/append mode
'''},
{'date': 'Mon Jul 13 2020 14:23:56.760 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''r ['rwa']
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 61
    with Open("x.txt", "r") as no:
  module <module> line 40
    self.__enter__()
  module <module> line 46
    self.filehandle = self.__enter[self.mode](self.filename)
  module <module> line 27
    raise FileNotFoundError(n)
FileNotFoundError: x.txt
'''},
{'date': 'Mon Jul 13 2020 14:24:41.683 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''r ['rwa']
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 61
    with Open("name.txt", "r") as no:
  module <module> line 40
    self.__enter__()
  module <module> line 46
    self.filehandle = self.__enter[self.mode](self.filename)
  module <module> line 27
    raise FileNotFoundError(n)
FileNotFoundError: name.txt
'''},
{'date': 'Mon Jul 13 2020 14:25:19.92 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''r ['rwa']
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 61
    with Open("names.txt", "r") as no:
  module <module> line 40
    self.__enter__()
  module <module> line 46
    self.filehandle = self.__enter[self.mode](self.filename)
  module <module> line 27
    raise FileNotFoundError(n)
FileNotFoundError: names.txt
'''},
{'date': 'Tue Jul 14 2020 16:16:29.840 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 79
    f = Open("nome.txt")
  module <module> line 58
    self.filename = filename
NameError: name 'filename' is not defined
'''},
{'date': 'Tue Jul 14 2020 16:16:33.521 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 79
    f = Open("nome.txt")
  module <module> line 58
    self.filename = filename
NameError: name 'filename' is not defined
'''},
{'date': 'Tue Jul 14 2020 16:18:33.630 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 79
    f = Open("nome.txt")
  module <module> line 58
    self.filename = filename
NameError: name 'filename' is not defined
'''},
{'date': 'Mon Jul 20 2020 16:56:14.454 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module browser.window line 1
  <!DOCTYPE html>
  ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 20 2020 17:39:40.363 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 53
    class App:
  module <module> line 80
    @section(h+w+p)
NameError: name 'h' is not defined
'''},
{'date': 'Mon Jul 20 2020 17:43:31.170 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 53
    class App:
  module <module> line 80
    @section(h+w+p)
  module <module> line 44
    super().init(func, clazz=clazz, oid=oid, tag=S)
AttributeError: object 'super' has no attribute 'init'
'''},
{'date': 'Mon Jul 20 2020 17:44:12.716 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 53
    class App:
  module <module> line 80
    @section(h+w+p)
  module <module> line 44
    super().__init__(func, clazz=clazz, oid=oid, tag=S)
  module <module> line 34
    functools.update_wrapper(self, func)  ## TA-DA! ##
  module functools line 59
    getattr(wrapper,attr). update(getattr(wrapped,attr,{}))
AttributeError: str has no attribute '__dict__'
'''},
{'date': 'Mon Jul 20 2020 17:45:26.446 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 53
    class App:
  module <module> line 80
    @section(h+w+p)
  module <module> line 44
    super().__init__(func, clazz=clazz, oid=oid, tag=S)
  module <module> line 34
    functools.update_wrapper(self, func)  ## TA-DA! ##
  module functools line 59
    getattr(wrapper,attr). update(getattr(wrapped,attr,{}))
AttributeError: str has no attribute '__dict__'
'''},
{'date': 'Mon Jul 20 2020 17:56:53.439 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 80
  def topo(self):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 20 2020 18:00:29.545 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    class App:
  module <module> line 76
    @bulma(h)
  module <module> line 29
    functools.update_wrapper(self, func)  ## TA-DA! ##
  module functools line 59
    getattr(wrapper,attr). update(getattr(wrapped,attr,{}))
AttributeError: str has no attribute '__dict__'
'''},
{'date': 'Mon Jul 20 2020 18:06:25.122 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 51
    class App:
  module <module> line 79
    @bulma(h)
  module <module> line 28
    self.func = func
NameError: name 'func' is not defined
'''},
{'date': 'Mon Jul 20 2020 18:08:31.906 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 50
    class App:
  module <module> line 78
    @section(h+w+p)
  module <module> line 41
    super().__init__(func, clazz=clazz, oid=oid, tag=S)
TypeError: __init__() got multiple values for argument 'clazz'
'''},
{'date': 'Thu Aug 20 2020 15:22:57.860 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 470
    Kwarwp(Jogo, medidas = STYLE) 
  module <module> line 346
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 385
    self.taba = {(i, j): fabrica[caracter].objeto(fabrica[caracter].url, x=i*lado, y=j*lado+lado, cena=cena)
  module <module> line 432
    vaga = Vazio("", x=x, y=y, cena=cena, ocupante=coisa)
  module <module> line 178
    self.acessa(ocupante)
  module <module> line 204
    ocupante.ocupa(self)
  module <module> line 257
    vaga.ocupou(self)
  module <module> line 214
    self.vazio.ocupa(ocupante)
  module _spy.vitollino.main line 586
    self.elt <= ocupante
TypeError: can't add 'Piche' object to DOMNode instance
'''},
{'date': 'Thu Aug 20 2020 15:29:48.927 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 470
    Kwarwp(Jogo, medidas = STYLE) 
  module <module> line 346
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 385
    self.taba = {(i, j): fabrica[caracter].objeto(fabrica[caracter].url, x=i*lado, y=j*lado+lado, cena=cena)
  module <module> line 419
    vaga = Vazio("", x=x, y=y, cena=cena, ocupante= coisa)
  module <module> line 178
    self.acessa(ocupante)
  module <module> line 204
    ocupante.ocupa(self)
  module <module> line 257
    vaga.ocupou(self)
  module <module> line 214
    self.vazio.ocupa(ocupante)
  module _spy.vitollino.main line 586
    self.elt <= ocupante
TypeError: can't add 'Oca' object to DOMNode instance
'''},
{'date': 'Thu Aug 20 2020 16:12:37.701 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 230
  fabrica = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Aug 20 2020 16:22:01.226 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 371
    Kwarwp(Jogo, mapa=MAPA_INICIO)
  module <module> line 203
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 237
    self.taba = {(i, j): fabrica[imagem].objeto(fabrica[imagem].imagem, x=i*lado, y=j*lado+lado, cena=cena)
  module <module> line 265
    vaga = Vazio(imagem, x=x, y=y, cena=cena, ocupante=self)
  module angie.kwarwpart line 55
    Kwarwp.VITOLLINO = Kwarwp.VITOLLINO or Jogo()
AttributeError: 'module' object has no attribute 'VITOLLINO'
'''},
{'date': 'Thu Aug 20 2020 16:53:42.513 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 383
    Kwarwp(Jogo, mapa=MAPA_INICIO)
  module <module> line 215
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 249
    self.taba = {(i, j): fabrica[imagem].objeto(fabrica[imagem].imagem, x=i*lado, y=j*lado+lado, cena=cena)
  module <module> line 337
    coisa = Oca(imagem, x=0, y=0, cena=cena, taba=self)
  module angie.kwarwpart line 155
    Kwarwp.VITOLLINO = Kwarwp.VITOLLINO or Jogo()
AttributeError: 'module' object has no attribute 'VITOLLINO'
'''},
{'date': 'Thu Aug 20 2020 17:22:33.751 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 127
  self.indio.siz = (lado*3, lado*4)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Sep 06 2020 11:18:18.37 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 65
    print(help(int))
IOError: File http://supygirls.pythonanywhere.com/js/builtins_docstrings.js not found
'''},
{'date': 'Mon Sep 14 2020 09:13:12.139 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 10:07:22.825 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 10:11:01.227 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 10:27:59.209 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 10:42:25.381 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 10:50:58.173 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 11:01:37.224 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 178
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 43
    Aldeia(Jogo())
  module <module> line 32
    a = [elt(x,y) for x in range(4) for y in range(3)]
  module <module> line 18
    ald=j.a(self.ALDEIA, x=x*150, y=y*150, w=tile, h=tile, style=dict(transform="rotate(90deg)"))
NameError: name 'tile' is not defined
'''},
{'date': 'Mon Sep 14 2020 11:04:32.524 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 178
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 44
    Aldeia(Jogo())
  module <module> line 34
    b = [spr(a[x*4+y], x, y) for x in range(4) for y in range(3)]
IndexError: list index out of range
'''},
{'date': 'Mon Sep 14 2020 11:16:15.196 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 11:31:13.930 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
SyntaxError: invalid syntax

 module __ge703 line 2
  UTF8 -*-# Este arquivo é parte do programa Vi:
          ^
'''},
{'date': 'Mon Sep 14 2020 11:33:56.677 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module __ge703 line 2
  UTF8 -*-# Este arquivo é parte do programa Vi:
          ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 11:34:22.133 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module __ge703 line 2
  UTF8 -*-# Este arquivo é parte do programa Vi:
          ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 12:03:43.184 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 12:18:54.946 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 12:21:45.276 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 12:23:26.517 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 12:43:08.75 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''  File <string>, line 13
    class Piso
               ^
SyntaxError: invalid syntax 
'''},
{'date': 'Mon Sep 14 2020 13:00:26.256 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''  File <string>, line 13
    class Piso
               ^
SyntaxError: invalid syntax 
'''},
{'date': 'Mon Sep 14 2020 13:17:57.648 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 13:19:03.944 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 13:24:08.560 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''  File <string>, line 13
    class Piso
               ^
SyntaxError: invalid syntax 
'''},
{'date': 'Mon Sep 14 2020 13:32:36.107 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 13:37:16.722 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 13:38:36.572 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 15:29:21.400 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 15:31:00.521 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 15:37:29.239 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 15:47:16.885 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
SyntaxError: invalid syntax

 module <string> line 21
  def possize(pos, siz=None)
                             ^
'''},
{'date': 'Mon Sep 14 2020 15:47:42.227 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
SyntaxError: invalid syntax

 module __ge703 line 2
  UTF8 -*-# Este arquivo é parte do programa Vi:
          ^
'''},
{'date': 'Mon Sep 14 2020 16:07:07.10 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  def possize(pos, siz=None)
                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 16:07:32.297 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module __ge703 line 2
  UTF8 -*-# Este arquivo é parte do programa Vi:
          ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 16:09:01.31 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 16:09:26.327 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': ''''''},
{'date': 'Mon Sep 14 2020 16:10:47.686 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  def possize(pos, siz=None)
                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 16:11:05.142 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 178
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 136
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 311
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 283
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 300
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 59
    Aldeia(Jogo())
  module <module> line 47
    a = [Piso(x, y, (-x*tile, -y*tile), (tile*4, tile*3), cena=cena)
NameError: name 'tile' is not defined
'''},
{'date': 'Mon Sep 14 2020 16:17:04.732 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  self.elt = Aldeia.J.a(self.ALDEIA, x=x*150, y=y*150, w=tile, h=tile, cena=cena, style=dict(transform:f"rotate({az}deg)"))
                                                                                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 16:19:12.251 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 33
  a = [Piso(x, y, (-x*tile, -y*tile), (tile*4, tile*3), cena=cena, 90)
                                                                     ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Mon Sep 14 2020 16:20:38.259 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 33
  a = [Piso(x, y, (-x*tile, -y*tile), (tile*4, tile*3), cena=cena)
                                                                            ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 16:50:09.892 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  azz = {key: nk*90 for nk, key in enumerate("NLSO")
                                                              ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 14 2020 16:51:22.533 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 178
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 136
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 311
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 283
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 300
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    Aldeia(Jogo())
  module <module> line 36
    a = [Piso(cena, x, y, ai+"N" ) for ai in "ABCDEFGHIJKL" ]
NameError: name 'x' is not defined
'''},
{'date': 'Mon Sep 14 2020 16:53:03.112 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 178
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 136
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 311
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 283
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 300
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    Aldeia(Jogo())
  module <module> line 36
    a = [Piso(cena, nk%4, nk//4, ai+"N" ) for nk, key in enumerate("ABCDEFGHIJKL")]
NameError: name 'ai' is not defined
'''},
{'date': 'Mon Sep 14 2020 16:53:19.992 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 178
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 136
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 311
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 283
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 300
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    Aldeia(Jogo())
  module <module> line 36
    a = [Piso(cena, nk%4, nk//4, ai+"N" ) for nk, ai in enumerate("ABCDEFGHIJKL")]
TypeError: __init__ missing 1 positional argument: 'siz'
'''},
{'date': 'Tue Sep 15 2020 14:52:17.423 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    Aldeia(Jogo())
  module <module> line 47
    j.a(ESPRIT, x=210, y=210,w=80, h=80, cena=cena)
NameError: name 'ESPRIT' is not defined
'''},
{'date': 'Tue Sep 15 2020 14:52:37.564 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    Aldeia(Jogo())
  module <module> line 47
    j.a(self.ESPRIT, x=210, y=210,w=80, h=80, cena=cena)
AttributeError: 'Aldeia' object has no attribute 'ESPRIT'
'''},
{'date': 'Tue Sep 15 2020 15:35:37.760 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 80
    Aldeia(Jogo())
  module <module> line 49
    self.guia()
  module <module> line 57
    Letra(cena, 0, 0, "A")
  module <module> line 18
    la.elt.html = chr(OFF+lt)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
'''},
{'date': 'Tue Sep 15 2020 15:37:39.519 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    Aldeia(Jogo())
  module <module> line 49
    self.guia()
  module <module> line 57
    d = [Piso(cena, nk%4*150, nk//4*150, lt ) for nk, lt in enumerate("ABCDEFGHIJKL")]
  module <module> line 29
    az = azz[ai[1]]
IndexError: string index out of range
'''},
{'date': 'Tue Sep 15 2020 23:27:50.945 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 135
    desafio2()
  module <module> line 128
    circus(3, MASMORRA)
  module <module> line 98
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 92
    self.desafios[desafio](solucao)
IndexError: list index out of range
'''},
{'date': 'Tue Sep 15 2020 23:32:24.964 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 135
    desafio2()
  module <module> line 128
    circus(3, MASMORRA)
  module <module> line 98
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 92
    self.desafios[desafio](solucao)
  module <module> line 84
    c = [Piso(self.cena, i*100, j*100, ai ) for i, linha in enumerate(solucao) for j, ai in enumerate(linha)]
  module <module> line 29
    az = azz[ai[1]]
IndexError: string index out of range
'''},
{'date': 'Tue Sep 15 2020 23:38:21.156 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 135
    desafio2()
  module <module> line 128
    circus(3, MASMORRA)
  module <module> line 98
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 92
    self.desafios[desafio](solucao)
  module <module> line 87
    c = [Piso(self.cena, i*100, j*100, solucao(ai) ) 
TypeError: 'dict' object is not callable
'''},
{'date': 'Tue Sep 15 2020 23:39:18.294 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 135
    desafio2()
  module <module> line 128
    circus(3, MASMORRA)
  module <module> line 98
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 92
    self.desafios[desafio](solucao)
  module <module> line 84
    c = [Piso(self.cena, i*100, j*100, ai ) for i, linha in enumerate(solucao) for j, ai in enumerate(linha)]
  module <module> line 29
    az = azz[ai[1]]
IndexError: string index out of range
'''},
{'date': 'Tue Sep 15 2020 23:41:10.942 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 135
    desafio2()
  module <module> line 128
    circus(3, MASMORRA)
  module <module> line 98
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 92
    self.desafios[desafio](solucao)
  module <module> line 84
    c = [Piso(self.cena, i*100, j*100, ai ) for i, linha in enumerate(solucao) for j, ai in enumerate(linha)]
  module <module> line 29
    az = azz[ai[1]]
IndexError: string index out of range
'''},
{'date': 'Tue Sep 15 2020 23:48:19.257 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 136
    desafio2()
  module <module> line 129
    circus(3, MASMORRA)
  module <module> line 99
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 93
    self.desafios[desafio](solucao)
  module <module> line 84
    c = [Piso(self.cena, i*100, j*100, ai ) for i, linha in enumerate(solucao) for j, ai in enumerate(linha)]
  module <module> line 29
    az = azz[ai[1]]
IndexError: string index out of range
'''},
{'date': 'Tue Sep 15 2020 23:50:49.422 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    desafio2()
  module <module> line 126
    circus(3, MASMORRA)
  module <module> line 96
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 53
    self.desafios = [self.guia, self.desafio0, self.desafio0, self.desafio1, self.desafio2]
AttributeError: 'Aldeia' object has no attribute 'desafio2'
'''},
{'date': 'Tue Sep 15 2020 23:51:32.73 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    desafio2()
  module <module> line 126
    circus(3, MASMORRA)
  module <module> line 96
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 90
    self.desafios[desafio](solucao)
  module <module> line 86
    desafio0(c)
TypeError: desafio0() takes 0 positional argument but more were given
'''},
{'date': 'Tue Sep 15 2020 23:53:16.456 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    desafio2()
  module <module> line 126
    circus(3, MASMORRA)
  module <module> line 96
    Aldeia(Jogo()).circus(desafio, solucao)
  module <module> line 90
    self.desafios[desafio](solucao)
  module <module> line 86
    desafio0(c)
TypeError: desafio0() takes 0 positional argument but more were given
'''},