
{'date': 'Thu Jul 09 2020 17:03:22.818 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 7
  CENA_PRAIA = "https://i.imgur.com/zOxshRh.jpg'
                                                ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Thu Jul 09 2020 17:03:50.220 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 7
  CENA_PRAIA = "https://i.imgur.com/zOxshRh.jpg'
                                                ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Thu Jul 09 2020 17:04:49.425 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 7
  CENA_PRAIA = "https://i.imgur.com/zOxshRh.jpg'
                                                ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Thu Jul 09 2020 17:05:03.327 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  """Mostra a cena da praia """"
                                ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Thu Jul 09 2020 17:05:09.310 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  """ Mostra a cena da praia """"
                                 ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Thu Jul 09 2020 17:05:19.297 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  """ Mostra a cena da praia """"
                                 ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Thu Jul 09 2020 17:05:33.462 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    Calcada().vai()
TypeError: vai() takes 0 positional argument but more were given
'''},
{'date': 'Thu Jul 09 2020 17:05:59.986 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    Calcada().vai()
  module <module> line 13
    Cena(CENA_PRAIA).vai()
TypeError: 'module' object is not callable
'''},
{'date': 'Thu Jul 09 2020 17:06:42.846 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    Calcada().vai()
  module <module> line 13
    Cena(CENA_CALCADA).vai()
TypeError: 'module' object is not callable
'''},
{'date': 'Thu Jul 09 2020 17:07:04.763 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    Calcada().vai()
  module <module> line 13
    Cena(CENA_CALCADA).vai()
TypeError: 'module' object is not callable
'''},
{'date': 'Thu Jul 09 2020 17:08:26.767 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 16
    Calcada().vai()
  module <module> line 14
    Cena(CENA_CALCADA).vai()
TypeError: 'module' object is not callable
'''},
{'date': 'Thu Jul 09 2020 17:17:33.91 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  if __name__ == "__main__"
                            ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Jul 09 2020 17:26:51.447 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    from _spy.vitollino.main import Cena, Element
ImportError: cannot import name 'Element'

ImportError
Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 264
    action()
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    from _spy.vitollino.main import Cena, Element
'''},
{'date': 'Thu Jul 09 2020 17:27:05.477 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 24
    Calcada().vai()
TypeError: __init__() takes 0 positional argument but more were given
'''},
{'date': 'Thu Jul 09 2020 17:27:43.560 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 24
    Calcada().vai()
TypeError: __init__() takes 0 positional argument but more were given
'''},
{'date': 'Thu Jul 30 2020 15:52:23.135 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 14
  from _spy.vitollino as v
                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Jul 30 2020 15:52:49.843 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 14
  from _spy.vitollino as v
                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Jul 30 2020 15:52:59.245 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 45
    Kwarwp().cria()
  module <module> line 29
    self.v = vitollino()
TypeError: 'NoneType' object is not callable
'''},
{'date': 'Thu Jul 30 2020 15:57:28.55 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 14
  from _spy.vitollino.main
                          ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Jul 30 2020 15:57:56.585 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from _spy.vitollino.main import Vitollino as v
ImportError: cannot import name 'Vitollino'

ImportError
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 264
    action()
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    from _spy.vitollino.main import Vitollino as v
'''},
{'date': 'Thu Jul 30 2020 15:58:44.460 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 47
    Kwarwp().cria()
  module <module> line 31
    self.v = vitollino()
TypeError: 'NoneType' object is not callable
'''},
{'date': 'Thu Jul 30 2020 16:21:45.132 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  GLIFOS = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 04 2020 20:23:57.183 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 21
    class Kwarwp():
  module <module> line 27
    def __init__(self, vitollino=None, mapa=MAPA_INICIO, medidas={}):
NameError: name 'MAPA_INICIO' is not defined
'''},
{'date': 'Tue Aug 04 2020 20:24:34.893 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 88
    Kwarwp(Jogo)
  module <module> line 45
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 50
    fabrica = {
  module <module> line 1
    (IMGUR)
NameError: name 'IMGUR' is not defined
'''},
{'date': 'Tue Aug 04 2020 20:26:05.233 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 90
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 52
    fabrica = {
AttributeError: 'Kwarwp' object has no attribute 'vazio'
'''},
{'date': 'Tue Aug 04 2020 20:26:31.453 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 91
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 53
    fabrica = {
AttributeError: 'Kwarwp' object has no attribute 'vazio'
'''},
{'date': 'Tue Aug 04 2020 20:27:23.347 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 91
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 53
    fabrica = {
AttributeError: 'Kwarwp' object has no attribute 'vazio'
'''},
{'date': 'Tue Aug 04 2020 20:29:44.357 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 92
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 54
    fabrica = {
AttributeError: 'Kwarwp' object has no attribute 'vazio'
'''},
{'date': 'Tue Aug 04 2020 20:30:15.27 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 91
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 54
    fabrica = {"&": Fab(self.coisa, f"{IMGUR}dZQ8liT.jpg"), # OCA
AttributeError: 'Kwarwp' object has no attribute 'vazio'
'''},
{'date': 'Tue Aug 04 2020 20:31:40.25 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 92
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 52
    Fab = nt("Fab. objeto", "imagem")
  module _collections line 495
    raise ValueError('Type names and field names can only contain alphanumeric characters and underscores: %r'%name)
ValueError: Type names and field names can only contain alphanumeric characters and underscores: 'Fab. objeto'
'''},
{'date': 'Tue Aug 04 2020 20:31:48.581 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 92
    Kwarwp(Jogo)
  module <module> line 47
    self.cena = self.cria(mapa=self.mapa) if vitollino else None
  module <module> line 52
    Fab = nt("Fab. objeto", "imagem")
  module _collections line 495
    raise ValueError('Type names and field names can only contain alphanumeric characters and underscores: %r'%name)
ValueError: Type names and field names can only contain alphanumeric characters and underscores: 'Fab. objeto'
'''},