
{'date': 'Tue Jul 14 2020 17:21:48.828 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Olá, Papai Noel !
Quantos presentes você pode distribuir? 35184372088832
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 9
    random.shuffle(s,random.random)
AttributeError: 'function' object has no attribute 'shuffle'
'''},
{'date': 'Tue Jul 14 2020 17:27:49.42 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 8
  1="http://activufrj.nce.ufrj.br/file/info/ProgOO/Card_pycharm.png"
   ^
SyntaxError: can't assign to literal
'''},
{'date': 'Tue Jul 14 2020 17:37:21.267 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''[7, 9, 3, 5, 1]
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 13
    self.pycharm=Elemento(self.pycharm)
NameError: name 'Elemento' is not defined
'''},
{'date': 'Tue Jul 14 2020 17:37:51.920 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''[9, 3, 1, 7, 5]
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 13
    self.pycharm=Elemento(self.pycharm_)
NameError: name 'Elemento' is not defined
'''},
{'date': 'Tue Jul 14 2020 17:38:31.634 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''[1, 3, 5, 9, 7]
Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 13
    self.pycharm=Elemento(self.pycharm_)
NameError: name 'Elemento' is not defined
'''},
{'date': 'Tue Jul 14 2020 19:24:35.643 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    Eventos().vai()
  module <module> line 12
    self.calcada = Cena(self.CENA_CALCADA)
AttributeError: 'Eventos' object has no attribute 'CENA_CALCADA'
'''},
{'date': 'Tue Jul 14 2020 19:31:10.597 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    Eventos().vai()
  module <module> line 14
    self.dark_side = Elemento(self.DARK_SIDE, , x=100, y=100, cena=self.calcada)
AttributeError: 'Eventos' object has no attribute 'DARK_SIDE'
'''},
{'date': 'Tue Jul 14 2020 20:06:58.636 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    Eventos().vai()
  module <module> line 14
    self.dark_side = Elemento(self.DARK_SIDE, , x=100, y=100, cena=self.calcada)
AttributeError: 'Eventos' object has no attribute 'DARK_SIDE'
'''},
{'date': 'Tue Jul 14 2020 20:11:12.791 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 24
    Eventos().vai()
  module <module> line 13
    self.pycharm = Elemento(self.CARTA_PYCHARM, , x=100, y=200, cena=self.calcada)
AttributeError: 'Eventos' object has no attribute 'calcada'
'''},
{'date': 'Tue Jul 14 2020 20:31:12.297 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 30
    Eventos().vai()
  module <module> line 13
    self.tabuleiro = Cena(self.CENA_TABULEIRO,,x=400,y=200)
  module _spy.vitollino.main line 1001
    Cena.c(**kwargs)
  module _spy.vitollino.main line 1044
    imagem, kwargs = (imagem, {}) if isinstance(imagem, str) \
AttributeError: 'int' object has no attribute '__getitem__'
'''},
{'date': 'Tue Jul 14 2020 20:31:45.916 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 30
    Eventos().vai()
  module <module> line 13
    self.tabuleiro = Cena(self.CENA_TABULEIRO,,x=400,y=200, cena=self.tabuleiro)
AttributeError: 'Eventos' object has no attribute 'tabuleiro'
'''},
{'date': 'Tue Jul 14 2020 20:35:29.84 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 30
    Eventos().vai()
  module <module> line 14
    self.pycharm = Elemento(self.CARTA_PYCHARM, , x=200, y=200, cena=self.tabuleiro)
AttributeError: 'Eventos' object has no attribute 'tabuleiro'
'''},
{'date': 'Tue Jul 14 2020 20:43:59.596 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  1=self.pycharm
   ^
SyntaxError: can't assign to literal
'''},
{'date': 'Tue Jul 14 2020 21:02:29.171 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 28
  def embaralhar (self):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 15 2020 01:17:36.205 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 2
  def cartas():
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 15 2020 01:18:31.342 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 3
  carta1=Cena(img="http://activufrj.nce.ufrj.br/file/ProgOO/Card_pycharm.png?disp=inline")
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 15 2020 01:50:28.652 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 13
    cartas()
  module <module> line 9
    	random.shuffle(carta,random.random)
AttributeError: 'function' object has no attribute 'shuffle'
'''},
{'date': 'Wed Jul 15 2020 01:50:51.940 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    cartas()
  module <module> line 11
    	carta[0].vai()
AttributeError: 'int' object has no attribute 'vai'
'''},
{'date': 'Wed Jul 15 2020 01:52:02.509 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  carta[0].vai()=carta[0](x=400,y=500)
                ^
SyntaxError: can't assign to function call 
'''},
{'date': 'Wed Jul 15 2020 01:52:23.737 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    cartas()
  module <module> line 11
    	carta[0]=carta[0](x=400,y=500)
TypeError: __call__() got an unexpected keyword argument 'x'
'''},
{'date': 'Wed Jul 15 2020 18:32:34.9 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 123
    if _name_ == "_main_":
NameError: name '_name_' is not defined
'''},
{'date': 'Wed Jul 15 2020 18:49:38.508 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 123
    if _name_ == "_main_":
NameError: name '_name_' is not defined
'''},
{'date': 'Wed Jul 15 2020 18:53:08.893 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 124
    Game().vai()
  module <module> line 51
    self.create_2x5_cards()
  module <module> line 61
    self.card1a = Card("PyCharm", IMG_CARD_1, list_cards[0], Game.cena, Game.rule)
TypeError: object() takes no parameters
'''},
{'date': 'Wed Jul 15 2020 19:06:00.383 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 177
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Game().vai()
  module <module> line 53
    self.create_2x5_cards()
  module <module> line 63
    self.card1a = Card("PyCharm", IMG_CARD_1, list_cards[0], Game.cena, Game.rule)
  module <module> line 30
    self.Game.previous_selected_card("click",self.turnUp)
AttributeError: 'Card' object has no attribute 'Game'
'''},